# MySQL connection details
mysql:
  enabled: false # Should MySQL be enabled? If false, SQLite will be used instead.
  driver: 'com.mysql.cj.jdbc.Driver' # The driver to use, defaults to 'com.mysql.jdbc.Driver'.
  host: '127.0.0.1' # Hostname of the MySQL server, defaults to 'localhost'
  port: 3306 # Database port, 3306 is the default
  username: root # Username to connect to the MySQL server, defaults to 'root'
  password: 'password' # Password to connect to the MySQL server, defaults to 'password'
  database: privatemessages # Database to use, defaults to 'privatemessages'
# Commands section
commands:
  reload:
    name: reload
    permission: 'privatemessages.command.reload'
  message:
    name: message
    permission: 'privatemessages.command.message'
    aliases:
      - m
      - msg
      - w
      - whisper
      - tell
      - t
      - msg
  reply:
    name: reply
    permission: 'privatemessages.command.reply'
    aliases:
      - r
  ignore:
    name: ignore
    permission: 'privatemessages.command.ignore'
    aliases:
      - ignores
    add:
      name: add
      permission: 'privatemessages.command.ignore.add'
    remove:
      name: remove
      permission: 'privatemessages.command.ignore.remove'
    list:
      name: list
      permission: 'privatemessages.command.ignore.list'
      max-size: 10
  toggle-messages:
    name: togglemessages
    permission: 'privatemessages.command.togglemessages'
    aliases:
      - toggle-messages
  social-spy:
    name: socialspy
    permission: 'privatemessages.command.socialspy'
    aliases:
      - social-spy